[package]
name = "rust-jvm-demo"
version = "0.1.0"
authors = ["Travis Brown <travisrobertbrown@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
lto = true
opt-level = "s"

